### PR TITLE
[API] Gamepiece handling overhaul

### PR DESCRIPTION
**Pull request by oh-yes-0-fps**
## Overview
This is an exploration into what a unified `GamePiece` API may look like. The idea is for the `GamePiece` simulation object mimic the lifecycle of a gamepiece in real life. This means that the gamepiece object is not "dropped" until it is out of play and no matter what the `GamePiece` is doing or where it is, the object is the same. The `GamePiece` also still exists if the robot has intaken it.

### States
The `GamePiece` now represents a finite state machine with a dedicated set of data for each state.

The states include:
- `LIMBO` [The game piece is not in play]
- `ON_FIELD` [The game piece is on the field, available for intake]
- `IN_FLIGHT` [The game piece is in the air, moving towards a target]
- `HELD` [The game piece is being held by a robot]
### Events
The `GamePiece` can also be subjected to events that can run callbacks registered under those events.

The events include:
- `TARGET_REACHED`
- `LANDED`
- `INTAKEN`
- `SHOT`
- `EXPELLED`

## Next steps
More documentation, better intake logic and all of the gamepiece information to be implicitly flushed to network tables. I also think considering making `Velocity2d` and `Velocity3d` types would be of interest, `Twist` arent really right nor are translations.

### CODE REVIEW

**Review by oh-yes-0-fps — COMMENTED** [review]
I have not touched the template at all either cuz my ide wont give me intellisense on it :3

**Comment by oh-yes-0-fps** [comment]
Another thing is I personally think the library should add a better concept of what a `Robot` is beyond a drivetrain. One example is multiple intakes feeding into the same indexer (i.e. 254 2022, 118 2024). The new `GamePiece` API allows each gamepiece to be given its own transform in the robot, this could easily be implemented by the user by having a gamepiece queue and each index in the queue correlates with its own transform, the issue that this would need to change how the intake simulation currently handles gamepieces.

I think an easy solution would be having a `GamePieceStorage` object you can give to `IntakeSimulation` that allows not only `IntakeSimulation` to share the storage but also allows the user to keep a reference to the storage outside of the `IntakeSimulation` object for some other cool API plumbing.

**Comment by catr1xLiu** [comment]
### First, this is really impressive work, and I love it!

However, I have a few questions:

1. The code seems a bit complex to me. Could you explain the purpose of `GamePieceEvent` and `GamePieceEventHandler`?
2. Is `poseHistory` meant to display the trajectory of the game piece on AdvantageScope?
3. When the lifecycle of a game piece ends and it's marked as in a "limbo" state, does it remain in memory? (I understand PC memory is sufficient, but I have some concerns about potential memory leaks.)

### Here are a few potential suggestions to improve the new API:
1. While I like the idea of simulating the full lifecycle of game pieces, I'm not sure if other teams will find it useful, as it increases complexity.  Teams have varied intakes, indexers, and flywheels, some might not be interested in simulating the game piece's processing.  So I think it's better if we just drop the game piece once it’s intaken. 
2. It might be helpful to test the new API in Advanced_Swerve_Drive_Example; this could give a more comprehensive understanding of its functionality.
Of course, feel free to disagree with any of the above—I’m looking forward to seeing the new API for game pieces in action!

**Comment by oh-yes-0-fps** [comment]
When the gamepieces are in limbo they are still in memory. I was thinking of adding a way of clearing out limbo pieces from the arena. The reason I like the idea of the gamepiece object staying around even when you intake it is because it can make indexing and shooting logic closer to real life. For example in 2024, you could represent your gamepiece storage as an `Optional<GamePiece> storage` and the shooting logic would be as simple as `storage.ifPresent(gp -> gp.launch(localPose(), SHOT_VELO));`. The simulation itself asserts if you have a gamepiece or not.

**Comment by oh-yes-0-fps** [comment]
The purpose of the events and event handler is potentially for logging, game logic or even unit tests. For example if i want to test shooting in a unit test, i could attach to the game pieces hit target event and landed event and depending on which one triggers with a give time span the test either fails or succeeds. Not saying I would recommend others this exact use case but allowing user reactivity to simulation events is never a bad idea.

**Comment by catr1xLiu** [comment]
That makes sense, I've changed my mind on removing the game piece once intaken.  Youi're right that It would be easier for teams to simulate intake and shooter if we hold the game pieces as "intaken". 

 Just a small detail here: I think it would be better if we put all the game pieces intaken by an `IntakeSimulation` into a queue, so that shooters/indexers can process them.  (maybe robots can hold more than one game piece next year).

**Comment by catr1xLiu** [comment]
Here’s a summary of the next steps:

1. Clean up game pieces in the "limbo" state.
2. Modify IntakeSimulation to "hold" game pieces in the "intaken" state.
3. Test the new API in Advanced_Swerve_Drive_Example.

As always, thanks a lot for your suggestions! Looking forward to using the new API!

**Comment by catr1xLiu** [comment]
When you're finished with your work, please create a PR towards `dev` branch, thanks!

**Pull request closed without merging**
