### PR TITLE
Simplified swerve sim

### PR DESCRIPTION
**Pull request by GearBoxFox**
**Thank you for your contribution! Before submitting your pull request, please review the following:**

-----------------------------------------------------

# Simplified Swerve Simulation Class

Wrapped most of the needed SwerveSimulation parts into a single class for less advanced users, also updated the current SwerveModuleSimulation to use the newer MapleMotorSim. There are probably some missing Javadocs comments, but all the functionality is there, so I can start making a template project.

### CODE REVIEW

**Comment by catr1xLiu** [comment]
hey, can you make this PR point to motor-sim-control-loops?

**Comment by catr1xLiu** [comment]
it's nice work here, but the newer version of maple-motor-sim is using the CTRE style requests

**Comment by GearBoxFox** [comment]
Done, but there are now a few conflicts in the branch merge, and I don't have write access to resolve them.

**Comment by catr1xLiu** [comment]
thanks for the help!

**Pull request merged**
